apiVersion: v1
kind: Pod
metadata:
  name: featureflag-example
  annotations:
    businessFeature: implementation1
spec:
  containers:
  - name: app
    image: freegroup/kube-featureflag:1.0
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: false
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations

